// Mock data for development without Supabase

export const mockCompany = {
  id: "mock-company-id",
  company_name: "Demo Corporation Sdn Bhd",
  registration_no: "202301234567",
  email: "info@democorp.com.my",
  phone: "+60123456789",
  address: "123, Jalan Merdeka, 50000 Kuala Lumpur",
  business_type: "Technology Services",
  status: "active",
  created_at: new Date().toISOString(),
};

export const mockProfile = {
  id: "mock-user-id",
  company_id: mockCompany.id,
  full_name: "Admin User",
  email: "admin@democorp.com.my",
  status: "active",
  email_verified: true,
  verified_at: new Date().toISOString(),
  created_at: new Date().toISOString(),
  updated_at: new Date().toISOString(),
};

export const mockEmployees = [
  {
    id: "emp-1",
    full_name: "Sarah Tan",
    email: "sarah.tan@democorp.com.my",
    department: "Human Resources",
    position: "HR Manager",
    status: "active",
    joined_date: "2023-01-15",
  },
  {
    id: "emp-2",
    full_name: "Ahmad Ibrahim",
    email: "ahmad.ibrahim@democorp.com.my",
    department: "Finance",
    position: "Finance Manager",
    status: "active",
    joined_date: "2023-02-20",
  },
  {
    id: "emp-3",
    full_name: "Lim Wei Chen",
    email: "lim.weichen@democorp.com.my",
    department: "IT",
    position: "Senior Developer",
    status: "active",
    joined_date: "2023-03-10",
  },
  {
    id: "emp-4",
    full_name: "Priya Devi",
    email: "priya.devi@democorp.com.my",
    department: "Marketing",
    position: "Marketing Executive",
    status: "active",
    joined_date: "2023-04-05",
  },
  {
    id: "emp-5",
    full_name: "Kumar Raj",
    email: "kumar.raj@democorp.com.my",
    department: "Operations",
    position: "Operations Manager",
    status: "active",
    joined_date: "2023-05-12",
  },
];

export const mockLeaveRequests = [
  {
    id: "leave-1",
    employee_id: "emp-1",
    employee_name: "Sarah Tan",
    leave_type: "annual",
    start_date: "2024-12-23",
    end_date: "2024-12-27",
    days: 5,
    status: "pending",
    reason: "Year-end holiday",
    created_at: new Date().toISOString(),
  },
  {
    id: "leave-2",
    employee_id: "emp-3",
    employee_name: "Lim Wei Chen",
    leave_type: "sick",
    start_date: "2024-12-18",
    end_date: "2024-12-19",
    days: 2,
    status: "approved",
    reason: "Medical certificate attached",
    created_at: new Date().toISOString(),
  },
];

export const mockExpenses = [
  {
    id: "exp-1",
    employee_id: "emp-2",
    employee_name: "Ahmad Ibrahim",
    amount: 350.50,
    category: "Travel",
    description: "Client meeting transportation",
    status: "pending",
    date: "2024-12-15",
    receipt_url: null,
  },
  {
    id: "exp-2",
    employee_id: "emp-4",
    employee_name: "Priya Devi",
    amount: 125.00,
    category: "Meals",
    description: "Team lunch with clients",
    status: "approved",
    date: "2024-12-14",
    receipt_url: null,
  },
];

export const mockProjects = [
  {
    id: "proj-1",
    name: "ERP System Implementation",
    client: "ABC Manufacturing Sdn Bhd",
    status: "in_progress",
    budget: 150000,
    spent: 85000,
    start_date: "2024-01-15",
    end_date: "2025-06-30",
    progress: 65,
  },
  {
    id: "proj-2",
    name: "Website Redesign",
    client: "XYZ Retail Sdn Bhd",
    status: "in_progress",
    budget: 50000,
    spent: 30000,
    start_date: "2024-10-01",
    end_date: "2025-02-28",
    progress: 45,
  },
];

export const mockDashboardMetrics = {
  totalEmployees: mockEmployees.length,
  activeProjects: mockProjects.filter(p => p.status === "in_progress").length,
  pendingApprovals: mockLeaveRequests.filter(l => l.status === "pending").length + 
                    mockExpenses.filter(e => e.status === "pending").length,
  monthlyRevenue: 285000,
  cashPosition: 450000,
  complianceScore: 94,
};

export const mockComplianceDeadlines = [
  {
    id: "comp-1",
    title: "EPF Contribution",
    type: "epf",
    due_date: "2025-01-15",
    status: "upcoming",
    priority: "high",
  },
  {
    id: "comp-2",
    title: "SOCSO Submission",
    type: "socso",
    due_date: "2025-01-15",
    status: "upcoming",
    priority: "high",
  },
  {
    id: "comp-3",
    title: "Monthly Tax Filing",
    type: "lhdn",
    due_date: "2025-01-31",
    status: "pending",
    priority: "medium",
  },
];

// ============================================
// ATTENDANCE MANAGEMENT MOCK DATA
// ============================================

// Mock Employees for Attendance
export const mockAttendanceEmployees = [
  // IT Department
  { id: 'emp-att-01', full_name: 'Ahmad Hafiz', position: 'Senior Developer', department_id: 'dept-it', employee_number: 'EMP001', email: 'ahmad.hafiz@democorp.com.my' },
  { id: 'emp-att-02', full_name: 'Sarah Chen', position: 'DevOps Engineer', department_id: 'dept-it', employee_number: 'EMP002', email: 'sarah.chen@democorp.com.my' },
  { id: 'emp-att-03', full_name: 'Kumar Patel', position: 'QA Engineer', department_id: 'dept-it', employee_number: 'EMP003', email: 'kumar.patel@democorp.com.my' },
  
  // HR Department
  { id: 'emp-att-04', full_name: 'Siti Nurhaliza', position: 'HR Manager', department_id: 'dept-hr', employee_number: 'EMP004', email: 'siti.n@democorp.com.my' },
  { id: 'emp-att-05', full_name: 'David Lim', position: 'Recruiter', department_id: 'dept-hr', employee_number: 'EMP005', email: 'david.lim@democorp.com.my' },
  { id: 'emp-att-06', full_name: 'Priya Sharma', position: 'HR Assistant', department_id: 'dept-hr', employee_number: 'EMP006', email: 'priya.sharma@democorp.com.my' },
  
  // Finance Department
  { id: 'emp-att-07', full_name: 'Tan Wei Ming', position: 'Finance Manager', department_id: 'dept-fin', employee_number: 'EMP007', email: 'tan.wm@democorp.com.my' },
  { id: 'emp-att-08', full_name: 'Nurul Ain', position: 'Accountant', department_id: 'dept-fin', employee_number: 'EMP008', email: 'nurul.ain@democorp.com.my' },
  { id: 'emp-att-09', full_name: 'Robert Wong', position: 'Accounts Payable', department_id: 'dept-fin', employee_number: 'EMP009', email: 'robert.wong@democorp.com.my' },
  
  // Operations
  { id: 'emp-att-10', full_name: 'Raj Kumar', position: 'Operations Manager', department_id: 'dept-ops', employee_number: 'EMP010', email: 'raj.kumar@democorp.com.my' },
  { id: 'emp-att-11', full_name: 'Lim Hui Ying', position: 'Warehouse Supervisor', department_id: 'dept-ops', employee_number: 'EMP011', email: 'lim.hy@democorp.com.my' },
  { id: 'emp-att-12', full_name: 'Azman Abdullah', position: 'Warehouse Staff', department_id: 'dept-ops', employee_number: 'EMP012', email: 'azman.a@democorp.com.my' },
  
  // Sales & Marketing
  { id: 'emp-att-13', full_name: 'Jessica Tan', position: 'Sales Manager', department_id: 'dept-sales', employee_number: 'EMP013', email: 'jessica.tan@democorp.com.my' },
  { id: 'emp-att-14', full_name: 'Muhammad Faisal', position: 'Marketing Executive', department_id: 'dept-sales', employee_number: 'EMP014', email: 'm.faisal@democorp.com.my' },
  { id: 'emp-att-15', full_name: 'Aisha Rahman', position: 'Sales Representative', department_id: 'dept-sales', employee_number: 'EMP015', email: 'aisha.rahman@democorp.com.my' },
];

// Mock Work Sites
export const mockWorkSites = [
  {
    id: 'site-hq',
    site_name: 'HQ - Menara Axis, KL',
    address: '123, Jalan Merdeka, 50000 Kuala Lumpur',
    latitude: 3.1319,
    longitude: 101.6841,
    radius_meters: 100,
    is_active: true,
  },
  {
    id: 'site-pj',
    site_name: 'PJ Branch Office',
    address: '456, Jalan PJ, 46000 Petaling Jaya',
    latitude: 3.1073,
    longitude: 101.6067,
    radius_meters: 150,
    is_active: true,
  },
  {
    id: 'site-warehouse',
    site_name: 'Shah Alam Warehouse',
    address: '789, Jalan Perindustrian, 40000 Shah Alam',
    latitude: 3.0738,
    longitude: 101.5183,
    radius_meters: 200,
    is_active: true,
  },
];

// Mock Shifts
export const mockShifts = [
  {
    id: 'shift-morning',
    shift_name: 'Morning Shift',
    start_time: '09:00:00',
    end_time: '18:00:00',
    grace_period_minutes: 10,
    lunch_break_minutes: 60,
    is_active: true,
  },
  {
    id: 'shift-afternoon',
    shift_name: 'Afternoon Shift',
    start_time: '14:00:00',
    end_time: '22:00:00',
    grace_period_minutes: 10,
    lunch_break_minutes: 45,
    is_active: true,
  },
  {
    id: 'shift-night',
    shift_name: 'Night Shift',
    start_time: '22:00:00',
    end_time: '06:00:00',
    grace_period_minutes: 15,
    lunch_break_minutes: 30,
    is_active: true,
  },
];

// Helper to get current time and dates
const now = new Date();
const today = now.toISOString().split('T')[0];
const yesterday = new Date(now.getTime() - 24 * 60 * 60 * 1000).toISOString().split('T')[0];
const twoDaysAgo = new Date(now.getTime() - 2 * 24 * 60 * 60 * 1000).toISOString().split('T')[0];
const threeDaysAgo = new Date(now.getTime() - 3 * 24 * 60 * 60 * 1000).toISOString().split('T')[0];
const fourDaysAgo = new Date(now.getTime() - 4 * 24 * 60 * 60 * 1000).toISOString().split('T')[0];
const fiveDaysAgo = new Date(now.getTime() - 5 * 24 * 60 * 60 * 1000).toISOString().split('T')[0];
const sixDaysAgo = new Date(now.getTime() - 6 * 24 * 60 * 60 * 1000).toISOString().split('T')[0];
const sevenDaysAgo = new Date(now.getTime() - 7 * 24 * 60 * 60 * 1000).toISOString().split('T')[0];

// Mock Attendance Records
export const mockAttendanceRecords = [
  // ========== TODAY ==========
  // On Time - Working now
  {
    id: 'att-rec-001',
    employee_id: 'emp-att-01',
    site_id: 'site-hq',
    shift_id: 'shift-morning',
    attendance_date: today,
    clock_in_time: `${today}T08:55:00Z`,
    clock_out_time: null,
    clock_in_latitude: 3.1319,
    clock_in_longitude: 101.6841,
    clock_out_latitude: null,
    clock_out_longitude: null,
    status: 'on_time',
    hours_worked: 0,
    overtime_hours: 0,
    is_provisional: false,
    locked_for_payroll: false,
    is_manually_adjusted: false,
    correction_id: null,
    employees: { full_name: 'Ahmad Hafiz', position: 'Senior Developer', employee_number: 'EMP001' },
    work_sites: { site_name: 'HQ - Menara Axis, KL' },
  },
  {
    id: 'att-rec-002',
    employee_id: 'emp-att-02',
    site_id: 'site-hq',
    shift_id: 'shift-morning',
    attendance_date: today,
    clock_in_time: `${today}T08:58:00Z`,
    clock_out_time: null,
    clock_in_latitude: 3.1319,
    clock_in_longitude: 101.6841,
    status: 'on_time',
    hours_worked: 0,
    overtime_hours: 0,
    is_provisional: false,
    locked_for_payroll: false,
    is_manually_adjusted: false,
    employees: { full_name: 'Sarah Chen', position: 'DevOps Engineer', employee_number: 'EMP002' },
    work_sites: { site_name: 'HQ - Menara Axis, KL' },
  },
  {
    id: 'att-rec-003',
    employee_id: 'emp-att-07',
    site_id: 'site-hq',
    shift_id: 'shift-morning',
    attendance_date: today,
    clock_in_time: `${today}T08:52:00Z`,
    clock_out_time: null,
    status: 'on_time',
    hours_worked: 0,
    overtime_hours: 0,
    is_provisional: false,
    locked_for_payroll: false,
    is_manually_adjusted: false,
    employees: { full_name: 'Tan Wei Ming', position: 'Finance Manager', employee_number: 'EMP007' },
    work_sites: { site_name: 'HQ - Menara Axis, KL' },
  },
  
  // Late Arrivals - Today
  {
    id: 'att-rec-004',
    employee_id: 'emp-att-04',
    site_id: 'site-hq',
    shift_id: 'shift-morning',
    attendance_date: today,
    clock_in_time: `${today}T09:35:00Z`,
    clock_out_time: null,
    status: 'late',
    hours_worked: 0,
    overtime_hours: 0,
    is_provisional: false,
    locked_for_payroll: false,
    is_manually_adjusted: false,
    employees: { full_name: 'Siti Nurhaliza', position: 'HR Manager', employee_number: 'EMP004' },
    work_sites: { site_name: 'HQ - Menara Axis, KL' },
  },
  {
    id: 'att-rec-005',
    employee_id: 'emp-att-14',
    site_id: 'site-hq',
    shift_id: 'shift-morning',
    attendance_date: today,
    clock_in_time: `${today}T09:42:00Z`,
    clock_out_time: null,
    status: 'late',
    hours_worked: 0,
    overtime_hours: 0,
    is_provisional: false,
    locked_for_payroll: false,
    is_manually_adjusted: false,
    employees: { full_name: 'Muhammad Faisal', position: 'Marketing Executive', employee_number: 'EMP014' },
    work_sites: { site_name: 'HQ - Menara Axis, KL' },
  },
  {
    id: 'att-rec-006',
    employee_id: 'emp-att-09',
    site_id: 'site-hq',
    shift_id: 'shift-morning',
    attendance_date: today,
    clock_in_time: `${today}T10:18:00Z`,
    clock_out_time: null,
    status: 'late',
    hours_worked: 0,
    overtime_hours: 0,
    is_provisional: false,
    locked_for_payroll: false,
    is_manually_adjusted: false,
    employees: { full_name: 'Robert Wong', position: 'Accounts Payable', employee_number: 'EMP009' },
    work_sites: { site_name: 'HQ - Menara Axis, KL' },
  },
  
  // Half Day - Very Late
  {
    id: 'att-rec-007',
    employee_id: 'emp-att-11',
    site_id: 'site-warehouse',
    shift_id: 'shift-morning',
    attendance_date: today,
    clock_in_time: `${today}T13:20:00Z`,
    clock_out_time: null,
    clock_in_latitude: 3.0738,
    clock_in_longitude: 101.5183,
    status: 'half_day',
    hours_worked: 0,
    overtime_hours: 0,
    is_provisional: false,
    locked_for_payroll: false,
    is_manually_adjusted: false,
    employees: { full_name: 'Lim Hui Ying', position: 'Warehouse Supervisor', employee_number: 'EMP011' },
    work_sites: { site_name: 'Shah Alam Warehouse' },
  },
  
  // Absent - No Show
  {
    id: 'att-rec-008',
    employee_id: 'emp-att-06',
    site_id: 'site-hq',
    shift_id: 'shift-morning',
    attendance_date: today,
    clock_in_time: null,
    clock_out_time: null,
    status: 'absent',
    hours_worked: 0,
    overtime_hours: 0,
    is_provisional: false,
    locked_for_payroll: false,
    is_manually_adjusted: false,
    employees: { full_name: 'Priya Sharma', position: 'HR Assistant', employee_number: 'EMP006' },
    work_sites: { site_name: 'HQ - Menara Axis, KL' },
  },
  {
    id: 'att-rec-009',
    employee_id: 'emp-att-15',
    site_id: 'site-hq',
    shift_id: 'shift-morning',
    attendance_date: today,
    clock_in_time: null,
    clock_out_time: null,
    status: 'absent',
    hours_worked: 0,
    overtime_hours: 0,
    is_provisional: false,
    locked_for_payroll: false,
    is_manually_adjusted: false,
    employees: { full_name: 'Aisha Rahman', position: 'Sales Representative', employee_number: 'EMP015' },
    work_sites: { site_name: 'HQ - Menara Axis, KL' },
  },
  
  // ========== YESTERDAY ==========
  // Provisional - Forgot to clock out
  {
    id: 'att-rec-010',
    employee_id: 'emp-att-03',
    site_id: 'site-hq',
    shift_id: 'shift-morning',
    attendance_date: yesterday,
    clock_in_time: `${yesterday}T08:50:00Z`,
    clock_out_time: `${yesterday}T18:00:00Z`,
    clock_in_latitude: 3.1319,
    clock_in_longitude: 101.6841,
    status: 'on_time',
    hours_worked: 8.17,
    overtime_hours: 0,
    is_provisional: true,
    locked_for_payroll: false,
    is_manually_adjusted: false,
    employees: { full_name: 'Kumar Patel', position: 'QA Engineer', employee_number: 'EMP003' },
    work_sites: { site_name: 'HQ - Menara Axis, KL' },
  },
  {
    id: 'att-rec-011',
    employee_id: 'emp-att-08',
    site_id: 'site-hq',
    shift_id: 'shift-morning',
    attendance_date: yesterday,
    clock_in_time: null,
    clock_out_time: `${yesterday}T18:05:00Z`,
    status: 'absent',
    hours_worked: 0,
    overtime_hours: 0,
    is_provisional: true,
    locked_for_payroll: false,
    is_manually_adjusted: false,
    employees: { full_name: 'Nurul Ain', position: 'Accountant', employee_number: 'EMP008' },
    work_sites: { site_name: 'HQ - Menara Axis, KL' },
  },
  
  // Normal completed day with overtime
  {
    id: 'att-rec-012',
    employee_id: 'emp-att-07',
    site_id: 'site-hq',
    shift_id: 'shift-morning',
    attendance_date: yesterday,
    clock_in_time: `${yesterday}T08:45:00Z`,
    clock_out_time: `${yesterday}T20:35:00Z`,
    status: 'on_time',
    hours_worked: 10.83,
    overtime_hours: 2.58,
    is_provisional: false,
    locked_for_payroll: false,
    is_manually_adjusted: false,
    employees: { full_name: 'Tan Wei Ming', position: 'Finance Manager', employee_number: 'EMP007' },
    work_sites: { site_name: 'HQ - Menara Axis, KL' },
  },
  {
    id: 'att-rec-013',
    employee_id: 'emp-att-13',
    site_id: 'site-hq',
    shift_id: 'shift-morning',
    attendance_date: yesterday,
    clock_in_time: `${yesterday}T08:58:00Z`,
    clock_out_time: `${yesterday}T18:10:00Z`,
    status: 'on_time',
    hours_worked: 8.2,
    overtime_hours: 0.17,
    is_provisional: false,
    locked_for_payroll: false,
    is_manually_adjusted: false,
    employees: { full_name: 'Jessica Tan', position: 'Sales Manager', employee_number: 'EMP013' },
    work_sites: { site_name: 'HQ - Menara Axis, KL' },
  },
  
  // ========== 2 DAYS AGO ==========
  {
    id: 'att-rec-014',
    employee_id: 'emp-att-01',
    site_id: 'site-hq',
    shift_id: 'shift-morning',
    attendance_date: twoDaysAgo,
    clock_in_time: `${twoDaysAgo}T08:50:00Z`,
    clock_out_time: `${twoDaysAgo}T18:05:00Z`,
    status: 'on_time',
    hours_worked: 8.25,
    overtime_hours: 0.08,
    is_provisional: false,
    locked_for_payroll: false,
    is_manually_adjusted: false,
    employees: { full_name: 'Ahmad Hafiz', position: 'Senior Developer', employee_number: 'EMP001' },
    work_sites: { site_name: 'HQ - Menara Axis, KL' },
  },
  {
    id: 'att-rec-015',
    employee_id: 'emp-att-02',
    site_id: 'site-hq',
    shift_id: 'shift-morning',
    attendance_date: twoDaysAgo,
    clock_in_time: `${twoDaysAgo}T08:52:00Z`,
    clock_out_time: `${twoDaysAgo}T21:15:00Z`,
    status: 'on_time',
    hours_worked: 11.38,
    overtime_hours: 3.25,
    is_provisional: false,
    locked_for_payroll: false,
    is_manually_adjusted: false,
    employees: { full_name: 'Sarah Chen', position: 'DevOps Engineer', employee_number: 'EMP002' },
    work_sites: { site_name: 'HQ - Menara Axis, KL' },
  },
  {
    id: 'att-rec-016',
    employee_id: 'emp-att-05',
    site_id: 'site-hq',
    shift_id: 'shift-morning',
    attendance_date: twoDaysAgo,
    clock_in_time: `${twoDaysAgo}T09:00:00Z`,
    clock_out_time: `${twoDaysAgo}T17:30:00Z`,
    status: 'on_time',
    hours_worked: 7.5,
    overtime_hours: 0,
    is_provisional: false,
    locked_for_payroll: false,
    is_manually_adjusted: true,
    correction_id: 'corr-req-004',
    employees: { full_name: 'David Lim', position: 'Recruiter', employee_number: 'EMP005' },
    work_sites: { site_name: 'HQ - Menara Axis, KL' },
  },
  
  // ========== 3 DAYS AGO ==========
  {
    id: 'att-rec-017',
    employee_id: 'emp-att-10',
    site_id: 'site-warehouse',
    shift_id: 'shift-morning',
    attendance_date: threeDaysAgo,
    clock_in_time: `${threeDaysAgo}T08:55:00Z`,
    clock_out_time: `${threeDaysAgo}T22:00:00Z`,
    clock_in_latitude: 3.0738,
    clock_in_longitude: 101.5183,
    status: 'on_time',
    hours_worked: 12.08,
    overtime_hours: 4.0,
    is_provisional: false,
    locked_for_payroll: false,
    is_manually_adjusted: false,
    employees: { full_name: 'Raj Kumar', position: 'Operations Manager', employee_number: 'EMP010' },
    work_sites: { site_name: 'Shah Alam Warehouse' },
  },
  {
    id: 'att-rec-018',
    employee_id: 'emp-att-12',
    site_id: 'site-warehouse',
    shift_id: 'shift-morning',
    attendance_date: threeDaysAgo,
    clock_in_time: `${threeDaysAgo}T09:00:00Z`,
    clock_out_time: `${threeDaysAgo}T18:00:00Z`,
    clock_in_latitude: 3.0738,
    clock_in_longitude: 101.5183,
    status: 'on_time',
    hours_worked: 8.0,
    overtime_hours: 0,
    is_provisional: false,
    locked_for_payroll: false,
    is_manually_adjusted: true,
    correction_id: 'corr-req-003',
    employees: { full_name: 'Azman Abdullah', position: 'Warehouse Staff', employee_number: 'EMP012' },
    work_sites: { site_name: 'Shah Alam Warehouse' },
  },
  
  // ========== 4 DAYS AGO ==========
  {
    id: 'att-rec-019',
    employee_id: 'emp-att-04',
    site_id: 'site-hq',
    shift_id: 'shift-morning',
    attendance_date: fourDaysAgo,
    clock_in_time: `${fourDaysAgo}T09:25:00Z`,
    clock_out_time: `${fourDaysAgo}T18:15:00Z`,
    status: 'late',
    hours_worked: 7.83,
    overtime_hours: 0.25,
    is_provisional: false,
    locked_for_payroll: false,
    is_manually_adjusted: false,
    employees: { full_name: 'Siti Nurhaliza', position: 'HR Manager', employee_number: 'EMP004' },
    work_sites: { site_name: 'HQ - Menara Axis, KL' },
  },
  {
    id: 'att-rec-020',
    employee_id: 'emp-att-14',
    site_id: 'site-hq',
    shift_id: 'shift-morning',
    attendance_date: fourDaysAgo,
    clock_in_time: `${fourDaysAgo}T09:15:00Z`,
    clock_out_time: `${fourDaysAgo}T18:00:00Z`,
    status: 'late',
    hours_worked: 7.75,
    overtime_hours: 0,
    is_provisional: false,
    locked_for_payroll: false,
    is_manually_adjusted: false,
    correction_id: 'corr-req-005',
    employees: { full_name: 'Muhammad Faisal', position: 'Marketing Executive', employee_number: 'EMP014' },
    work_sites: { site_name: 'HQ - Menara Axis, KL' },
  },
  
  // ========== 5 DAYS AGO ==========
  {
    id: 'att-rec-021',
    employee_id: 'emp-att-06',
    site_id: 'site-hq',
    shift_id: 'shift-morning',
    attendance_date: fiveDaysAgo,
    clock_in_time: `${fiveDaysAgo}T08:58:00Z`,
    clock_out_time: `${fiveDaysAgo}T18:00:00Z`,
    status: 'on_time',
    hours_worked: 8.03,
    overtime_hours: 0,
    is_provisional: true,
    locked_for_payroll: false,
    is_manually_adjusted: false,
    correction_id: 'corr-req-006',
    employees: { full_name: 'Priya Sharma', position: 'HR Assistant', employee_number: 'EMP006' },
    work_sites: { site_name: 'HQ - Menara Axis, KL' },
  },
  
  // ========== 7 DAYS AGO - LOCKED ==========
  {
    id: 'att-rec-022',
    employee_id: 'emp-att-01',
    site_id: 'site-hq',
    shift_id: 'shift-morning',
    attendance_date: sevenDaysAgo,
    clock_in_time: `${sevenDaysAgo}T08:55:00Z`,
    clock_out_time: `${sevenDaysAgo}T18:05:00Z`,
    status: 'on_time',
    hours_worked: 8.17,
    overtime_hours: 0.08,
    is_provisional: false,
    locked_for_payroll: true,
    is_manually_adjusted: false,
    employees: { full_name: 'Ahmad Hafiz', position: 'Senior Developer', employee_number: 'EMP001' },
    work_sites: { site_name: 'HQ - Menara Axis, KL' },
  },
  {
    id: 'att-rec-023',
    employee_id: 'emp-att-07',
    site_id: 'site-hq',
    shift_id: 'shift-morning',
    attendance_date: sevenDaysAgo,
    clock_in_time: `${sevenDaysAgo}T08:50:00Z`,
    clock_out_time: `${sevenDaysAgo}T18:00:00Z`,
    status: 'on_time',
    hours_worked: 8.17,
    overtime_hours: 0,
    is_provisional: false,
    locked_for_payroll: true,
    is_manually_adjusted: false,
    employees: { full_name: 'Tan Wei Ming', position: 'Finance Manager', employee_number: 'EMP007' },
    work_sites: { site_name: 'HQ - Menara Axis, KL' },
  },
];

// Mock Overtime Sessions
export const mockOvertimeSessions = [
  // ACTIVE OT SESSION (currently running)
  {
    id: 'ot-session-001',
    attendance_record_id: 'att-rec-013',
    employee_id: 'emp-att-13',
    site_id: 'site-hq',
    ot_in_time: `${yesterday}T18:15:00Z`,
    ot_in_latitude: 3.1319,
    ot_in_longitude: 101.6841,
    ot_out_time: null,
    ot_out_latitude: null,
    ot_out_longitude: null,
    total_ot_hours: 0,
    status: 'active',
    is_approved: false,
    approved_by: null,
    approved_at: null,
    auto_closed_at: null,
    created_at: `${yesterday}T18:15:00Z`,
    employees: { full_name: 'Jessica Tan', position: 'Sales Manager' },
    work_sites: { site_name: 'HQ - Menara Axis, KL' },
  },
  
  // COMPLETED - PENDING APPROVAL
  {
    id: 'ot-session-002',
    attendance_record_id: 'att-rec-012',
    employee_id: 'emp-att-07',
    site_id: 'site-hq',
    ot_in_time: `${yesterday}T18:05:00Z`,
    ot_in_latitude: 3.1319,
    ot_in_longitude: 101.6841,
    ot_out_time: `${yesterday}T20:35:00Z`,
    ot_out_latitude: 3.1319,
    ot_out_longitude: 101.6841,
    total_ot_hours: 2.5,
    status: 'completed',
    is_approved: false,
    approved_by: null,
    approved_at: null,
    auto_closed_at: null,
    created_at: `${yesterday}T18:05:00Z`,
    employees: { full_name: 'Tan Wei Ming', position: 'Finance Manager' },
    work_sites: { site_name: 'HQ - Menara Axis, KL' },
  },
  {
    id: 'ot-session-003',
    attendance_record_id: 'att-rec-014',
    employee_id: 'emp-att-01',
    site_id: 'site-hq',
    ot_in_time: `${twoDaysAgo}T18:05:00Z`,
    ot_out_time: `${twoDaysAgo}T19:30:00Z`,
    total_ot_hours: 1.42,
    status: 'completed',
    is_approved: false,
    approved_by: null,
    approved_at: null,
    auto_closed_at: null,
    created_at: `${twoDaysAgo}T18:05:00Z`,
    employees: { full_name: 'Ahmad Hafiz', position: 'Senior Developer' },
    work_sites: { site_name: 'HQ - Menara Axis, KL' },
  },
  
  // COMPLETED - APPROVED
  {
    id: 'ot-session-004',
    attendance_record_id: 'att-rec-015',
    employee_id: 'emp-att-02',
    site_id: 'site-hq',
    ot_in_time: `${twoDaysAgo}T18:00:00Z`,
    ot_out_time: `${twoDaysAgo}T21:15:00Z`,
    total_ot_hours: 3.25,
    status: 'completed',
    is_approved: true,
    approved_by: 'hr-manager-id',
    approved_at: `${yesterday}T09:30:00Z`,
    auto_closed_at: null,
    created_at: `${twoDaysAgo}T18:00:00Z`,
    employees: { full_name: 'Sarah Chen', position: 'DevOps Engineer' },
    work_sites: { site_name: 'HQ - Menara Axis, KL' },
  },
  
  // AUTO-CLOSED (exceeded 4 hours)
  {
    id: 'ot-session-005',
    attendance_record_id: 'att-rec-017',
    employee_id: 'emp-att-10',
    site_id: 'site-warehouse',
    ot_in_time: `${threeDaysAgo}T18:00:00Z`,
    ot_in_latitude: 3.0738,
    ot_in_longitude: 101.5183,
    ot_out_time: `${threeDaysAgo}T22:00:00Z`,
    ot_out_latitude: 3.0738,
    ot_out_longitude: 101.5183,
    total_ot_hours: 4.0,
    status: 'completed',
    is_approved: false,
    approved_by: null,
    approved_at: null,
    auto_closed_at: `${threeDaysAgo}T22:00:00Z`,
    created_at: `${threeDaysAgo}T18:00:00Z`,
    employees: { full_name: 'Raj Kumar', position: 'Operations Manager' },
    work_sites: { site_name: 'Shah Alam Warehouse' },
  },
];

// Mock Correction Requests
export const mockCorrectionRequests = [
  // PENDING - URGENT (deadline approaching)
  {
    id: 'corr-req-001',
    attendance_record_id: 'att-rec-010',
    employee_id: 'emp-att-03',
    correction_type: 'clock_out',
    requested_clock_in: null,
    requested_clock_out: `${yesterday}T19:45:00Z`,
    reason: 'I forgot to clock out yesterday. I left the office around 7:45 PM after finishing the sprint demo preparation. My manager can confirm I was in the meeting room until that time.',
    attachment_url: null,
    status: 'pending',
    reviewed_by: null,
    reviewed_at: null,
    reviewer_notes: null,
    submission_deadline: new Date(new Date(`${yesterday}T08:50:00Z`).getTime() + 24 * 60 * 60 * 1000).toISOString(),
    is_within_deadline: true,
    created_at: `${today}T10:30:00Z`,
    employees: { 
      full_name: 'Kumar Patel', 
      position: 'QA Engineer',
      employee_number: 'EMP003'
    },
  },
  
  // PENDING - NORMAL
  {
    id: 'corr-req-002',
    attendance_record_id: 'att-rec-011',
    employee_id: 'emp-att-08',
    correction_type: 'clock_in',
    requested_clock_in: `${yesterday}T08:40:00Z`,
    requested_clock_out: null,
    reason: 'My phone battery died and I couldn\'t clock in via the app. I arrived at 8:40 AM as usual and was seen by colleagues at the office pantry.',
    attachment_url: null,
    status: 'pending',
    reviewed_by: null,
    reviewed_at: null,
    reviewer_notes: null,
    submission_deadline: new Date(new Date(`${yesterday}T08:40:00Z`).getTime() + 24 * 60 * 60 * 1000).toISOString(),
    is_within_deadline: true,
    created_at: `${yesterday}T11:20:00Z`,
    employees: { 
      full_name: 'Nurul Ain', 
      position: 'Accountant',
      employee_number: 'EMP008'
    },
  },
  
  // PENDING - BOTH CLOCK IN AND OUT
  {
    id: 'corr-req-003',
    attendance_record_id: 'att-rec-018',
    employee_id: 'emp-att-12',
    correction_type: 'both',
    requested_clock_in: `${threeDaysAgo}T09:00:00Z`,
    requested_clock_out: `${threeDaysAgo}T18:00:00Z`,
    reason: 'GPS signal was weak at the warehouse location. The app showed errors when I tried to clock in and out. My supervisor witnessed my attendance.',
    attachment_url: null,
    status: 'pending',
    reviewed_by: null,
    reviewed_at: null,
    reviewer_notes: null,
    submission_deadline: new Date(new Date(`${threeDaysAgo}T09:00:00Z`).getTime() + 24 * 60 * 60 * 1000).toISOString(),
    is_within_deadline: true,
    created_at: `${threeDaysAgo}T19:15:00Z`,
    employees: { 
      full_name: 'Azman Abdullah', 
      position: 'Warehouse Staff',
      employee_number: 'EMP012'
    },
  },
  
  // APPROVED
  {
    id: 'corr-req-004',
    attendance_record_id: 'att-rec-016',
    employee_id: 'emp-att-05',
    correction_type: 'clock_out',
    requested_clock_in: null,
    requested_clock_out: `${twoDaysAgo}T17:30:00Z`,
    reason: 'System logged me out while I was in a client call. I actually left at 5:30 PM after the meeting.',
    attachment_url: null,
    status: 'approved',
    reviewed_by: 'hr-manager-id',
    reviewed_at: `${yesterday}T10:15:00Z`,
    reviewer_notes: 'Verified with team calendar. Client call was scheduled until 5:30 PM. Approved.',
    submission_deadline: new Date(new Date(`${twoDaysAgo}T09:00:00Z`).getTime() + 24 * 60 * 60 * 1000).toISOString(),
    is_within_deadline: true,
    created_at: `${twoDaysAgo}T18:45:00Z`,
    employees: { 
      full_name: 'David Lim', 
      position: 'Recruiter',
      employee_number: 'EMP005'
    },
  },
  {
    id: 'corr-req-007',
    attendance_record_id: 'att-rec-019',
    employee_id: 'emp-att-04',
    correction_type: 'clock_in',
    requested_clock_in: `${fourDaysAgo}T09:00:00Z`,
    requested_clock_out: null,
    reason: 'Traffic jam on LDP highway. I clocked in late but wanted to correct the time.',
    attachment_url: null,
    status: 'approved',
    reviewed_by: 'hr-manager-id',
    reviewed_at: `${threeDaysAgo}T14:20:00Z`,
    reviewer_notes: 'Verified late clock-in. However, actual clock-in was 9:25 AM, not 9:00 AM as requested. Approved actual time.',
    submission_deadline: new Date(new Date(`${fourDaysAgo}T09:25:00Z`).getTime() + 24 * 60 * 60 * 1000).toISOString(),
    is_within_deadline: true,
    created_at: `${fourDaysAgo}T16:30:00Z`,
    employees: { 
      full_name: 'Siti Nurhaliza', 
      position: 'HR Manager',
      employee_number: 'EMP004'
    },
  },
  
  // REJECTED
  {
    id: 'corr-req-005',
    attendance_record_id: 'att-rec-020',
    employee_id: 'emp-att-14',
    correction_type: 'clock_in',
    requested_clock_in: `${fourDaysAgo}T08:30:00Z`,
    requested_clock_out: null,
    reason: 'I arrived early but forgot to clock in.',
    attachment_url: null,
    status: 'rejected',
    reviewed_by: 'hr-manager-id',
    reviewed_at: `${threeDaysAgo}T14:30:00Z`,
    reviewer_notes: 'Security logs show entry at 9:15 AM, not 8:30 AM. Correction request does not match evidence.',
    submission_deadline: new Date(new Date(`${fourDaysAgo}T09:15:00Z`).getTime() + 24 * 60 * 60 * 1000).toISOString(),
    is_within_deadline: true,
    created_at: `${fourDaysAgo}T16:00:00Z`,
    employees: { 
      full_name: 'Muhammad Faisal', 
      position: 'Marketing Executive',
      employee_number: 'EMP014'
    },
  },
  
  // EXPIRED (deadline passed)
  {
    id: 'corr-req-006',
    attendance_record_id: 'att-rec-021',
    employee_id: 'emp-att-06',
    correction_type: 'clock_out',
    requested_clock_in: null,
    requested_clock_out: `${fiveDaysAgo}T18:00:00Z`,
    reason: 'Forgot to clock out.',
    attachment_url: null,
    status: 'pending',
    reviewed_by: null,
    reviewed_at: null,
    reviewer_notes: null,
    submission_deadline: new Date(new Date(`${fiveDaysAgo}T08:58:00Z`).getTime() + 24 * 60 * 60 * 1000).toISOString(),
    is_within_deadline: false,
    created_at: new Date(new Date(`${fiveDaysAgo}T08:58:00Z`).getTime() + 26 * 60 * 60 * 1000).toISOString(),
    employees: { 
      full_name: 'Priya Sharma', 
      position: 'HR Assistant',
      employee_number: 'EMP006'
    },
  },
];

// Mock Attendance Summary
export const mockAttendanceSummary = {
  present_count: 8,
  late_count: 3,
  absent_count: 2,
  provisional_count: 2,
  average_hours: 8.2,
  total_employees: 15,
  active_ot_sessions: 1,
  pending_ot_approval: 2,
  pending_corrections: 3,
  urgent_corrections: 1,
};
