project_id = "xrtgpkehiureaoxlxatu"

[functions.hr-employees]
verify_jwt = false

[functions.hr-departments]
verify_jwt = true

[functions.hr-attendance]
verify_jwt = true

[functions.register-company]
verify_jwt = false

[functions.send-verification-email]
verify_jwt = false